#!/bin/sh
MAXDEVICES=24
module="tip866drv"
ttydevice="ttySTIP866_"
cuadevice="cuaTIP866_"
ttyname="ttySTIP866_"
cuaname="cuaTIP866_"
MODE="666"

# remove old device nodes
rm -f /dev/${ttyname}*
rm -f /dev/${cuaname}*

# extract current major device numbers
ttymajor=`cat /proc/devices | awk "\\$2==\"$ttydevice\" {print \\$1}"`
cuamajor=`cat /proc/devices | awk "\\$2==\"$cuadevice\" {print \\$1}"`


# create special device nodes for TIP866 tty and cua devices 0..MAXDEVICES-1
for ((minor=0;minor<MAXDEVICES;minor++))
do
    mknod /dev/${ttyname}${minor} c $ttymajor ${minor}
    chmod ${MODE} /dev/${ttyname}${minor}
    mknod /dev/${cuaname}${minor} c $cuamajor ${minor}
    chmod ${MODE} /dev/${cuaname}${minor}
done

ls -la /dev/${ttyname}*
ls -la /dev/${cuaname}*
