#!/bin/sh
MAXDEVICES=24
module="tip866drv"
ttydevice="ttySTIP866_"
ttyname="ttySTIP866_"
MODE="666"

# remove old device nodes
rm -f /dev/${ttyname}*


# extract current major device numbers
ttymajor=`cat /proc/devices | awk "\\$2==\"$ttydevice\" {print \\$1}"`


# create special device nodes for TIP866 tty devices 0..MAXDEVICES-1
for ((minor=0;minor<MAXDEVICES;minor++))
do
    mknod /dev/${ttyname}${minor} c $ttymajor ${minor}
    chmod ${MODE} /dev/${ttyname}${minor}
done

ls -la /dev/${ttyname}*
