#! /bin/sh -e
### BEGIN INIT INFO
# Provides:          era
# Required-Start:    param_daemon
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: Start the CARMEN ERA module
### END INIT INFO

CARMEN="/usr/lib/carmen_robox/carmen.sh"

[ -e "$CARMEN" ] || exit 0
. $CARMEN
[ "$CARMEN_START_ERA" == 1 ] || exit 0

MODULE_NAME="era"
MODULE_BIN="/usr/bin/era"
MODULE_OPTS=""

export LD_LIBRARY_PATH=/usr/local/lib

[ -e "$MODULE_BIN" ] || exit 0

case "$1" in
  start)
    echo -n "Starting $MODULE_NAME module"
    carmen_start_module "$MODULE_BIN" "$MODULE_OPTS"
    echo "."
	;;
  stop)
    echo -n "Stopping $MODULE_NAME module"
    carmen_stop_module "$MODULE_BIN"
    echo "."
	;;
  restart)
    echo -n "Restarting $MODULE_NAME module"
    carmen_restart_module "$MODULE_BIN" "$MODULE_OPTS"
    echo "."
  ;;

  *)
	  echo "Usage: $0 {start|stop|restart}"
	  exit 1
esac

exit 0
