#! /bin/sh -e
### BEGIN INIT INFO
# Provides:          param_daemon
# Required-Start:    central
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: Start the CARMEN parameter daemon module
### END INIT INFO

function carmen_ini_update()
{
  cat $CARMEN_ROBOT_INI > $CARMEN_INI
  echo >> $CARMEN_INI
  echo >> $CARMEN_INI
  cat $CARMEN_ERA_INI >> $CARMEN_INI
}

CARMEN="/usr/lib/carmen_robox/carmen.sh"
CARMEN_INI="/etc/carmen_robox/robox.ini"

[ -e "$CARMEN" ] || exit 0
. $CARMEN
[ "$CARMEN_START_PARAM" == 1 ] || exit 0

MODULE_NAME="param_daemon"
MODULE_BIN="/usr/bin/carmen-param_daemon"
MODULE_OPTS="-r $CARMEN_ROBOT $CARMEN_INI"

[ -e "$MODULE_BIN" ] || exit 0

case "$1" in
  start)
    echo -n "Starting $MODULE_NAME module"
    carmen_ini_update
    carmen_start_module "$MODULE_BIN" "$MODULE_OPTS"
    echo "."
	;;
  stop)
    echo -n "Stopping $MODULE_NAME module"
    carmen_stop_module "$MODULE_BIN"
    echo "."
	;;
  restart)
    echo -n "Restarting $MODULE_NAME module"
    carmen_ini_update
    carmen_restart_module "$MODULE_BIN" "$MODULE_OPTS"
    echo "."
  ;;

  *)
	  echo "Usage: $0 {start|stop|restart}"
	  exit 1
esac

exit 0
